Revert "Add work profile support for the new Default apps UI."
This reverts commit 9ce4a3ce1cbe18ed4ec82d4f0a076c89343a598b.

Reason for revert: This broke mainline_modules-userdebug.

packages/apps/PermissionController/src/com/android/packageinstaller/role/model/RequiredActivity.java:47: error: cannot find symbol
return packageManager.queryIntentActivitiesAsUser(intent, flags, user);
^
symbol: method queryIntentActivitiesAsUser(Intent,int,UserHandle)
location: variable packageManager of type PackageManager
packages/apps/PermissionController/src/com/android/packageinstaller/role/model/RequiredContentProvider.java:47: error: cannot find symbol
return packageManager.queryIntentContentProvidersAsUser(intent, flags, user);
^
symbol: method queryIntentContentProvidersAsUser(Intent,int,UserHandle)
location: variable packageManager of type PackageManager
packages/apps/PermissionController/src/com/android/packageinstaller/role/model/RequiredService.java:47: error: cannot find symbol
return packageManager.queryIntentServicesAsUser(intent, flags, user);
^
symbol: method queryIntentServicesAsUser(Intent,int,UserHandle)
location: variable packageManager of type PackageManager
packages/apps/PermissionController/src/com/android/packageinstaller/role/utils/PackageUtils.java:92: error: cannot find symbol
return packageManager.getApplicationInfoAsUser(packageName,
^
symbol: method getApplicationInfoAsUser(String,int,UserHandle)
location: variable packageManager of type PackageManager
4 errors

Change-Id: Ia9c0e6ed2bd04f9656cf5de50b0d3cac190e49d0